const bikes =[
    {name:'Neiman Marcus Limited Edition Fighter',rating:'5',
    price:'11 Million',
    description:'This silver grated, devilish looking bike comes with an $11 million tag. Surprising it comes from a retail store brand, Neiman Marcus, which made only 25 Fighters. However, a single look leaves many longing to get a ride. The clockwork resembling body reaches a top speed of 190 miles per hour. ',
    img:'https://i.ibb.co/VmXpK6v/1-Neiman-Marcus-Limited-Edition-Fighter-11-Million.jpg'},
    {name:'1949 E90 AJS Porcupine',rating:'4.5',
    price:'11 Million',
    description:'Yamaha’s BMS Chopper and the air ride system completely changes the motorcycle’s look by removing the side stand. However, a $3 million price is not just for the performance. A closer look will show that the bike is sprinkled with real 24-karat gold. It uses a single-sided swingarm rear suspension. ',
    img:'https://i.ibb.co/kVT57LB/3-Ecosse-ES1-Spirit-3-6-Million.jpg'},
    {name:'The Yamaha BMS Chopper',rating:'4.5',
    price:'3 Million',
    description:'The 1949 E90 AJS Porcupine pegs its origin in British manufacturing brand Associated Motor Cycles who built the E90 exclusively for race tracks. Although it was the E95 that won AJS its only victory in FIM 500cc world championship, the E90 has its own worth that shows in its $7 million price. The E90 used a 500cc twin DOHC engine. ',
    img:'https://i.ibb.co/x69J9YL/4-The-Yamaha-BMS-Chopper-3-million.jpg'},
    {name:'Ecosse ES1 Spirit',rating:'5',
    price:'3.6 Million',
    description:'The tango colored sports bike, Ecosse ES1, sits well onto the million-dollar radar and with many impressive specs. The elements of the bike heavily involve a carbon fiber build and manage a top speed of 250 mph. Its low weight of mere 265lbs ensures easier handling. ',
    img:'https://i.ibb.co/dc1McFV/2-1949-E90-AJS-Porcupine-7-Million.jpg'},
    {name:'Harley Davidson Cosmic Starship',rating:'5',
    price:'1.5 million',
    description:'The Cosmic Starship is probably the most famous motorcycle in the lot and the price also soars to an eye-watering $1.5 million. Artist Jack Armstrong himself painted the bike and his original paintings themselves range from $300,000 to $3,000,000 so it’s understandable why Harley Davidson would place such a hefty price tag. ',
    img:'https://i.ibb.co/9ZyHdG3/5-Harley-Davidson-Cosmic-Starship-1-5-million.jpg'},
    {name:'Dodge Tomahawk V10 Superbike',rating:'4',
    price:'5,50000',
    description:'The Dodge Tomahawk’s extraordinary superpower is written in its title, the V10 Superbike. Valued at a price of $550,000, the bike comes with four wheels and has a 8.3-liter V10 SRT 10 engine installed that cranks out 500 horsepower. Being one of the fastest bikes in the world it has a top speed exceeding 300mph! ',
    img:'https://i.ibb.co/ChZpy7m/6-Dodge-Tomahawk-V10-Superbike-550000.jpg'},
    {name:'Vincent Black Shadow',rating:'4',
    price:'11 Million',
    description:'The legendary Vincent Black Shadow is one of the most expensive classic bikes present today. More than being expensive, it is extremely limited since only 33 units of this motorcycle were built back in 1948. The bike has two cylinders that give Jaguar like performance with 250cc power. The frame is elegantly trimmed that elicits that vintage charm',
    img:'https://i.ibb.co/2dwHXWb/7-Legendary-British-Vintage-Black-400000.jpg'}, 
    {name:'Ecosse Founder’s Edition Ti XX ',rating:'5',
    price:'300,000',
    description:'Ecosse’s Ti XXX is the perfect modern styled motorcycle that creatively inserts playful yellow-colored sparks on the body. It has a full titanium-built chassis and exhaust and is driven by a supercharged powertrain. The supercharged 2,409cc aluminum engine produces 225 horsepower. It also makes use of Carbon fiber to help keep the weight low ',
    img:'https://i.ibb.co/LtKQY6r/8-Ecosse-Founder-u2019s-Edition-Ti-XX-300000.jpg'},
    {name:'Ducati Desmosedici D16RR NCR M16',rating:'5',
    price:'235,000',
    description:'Ducatis Desmosedici jumped several steps ahead with its NCR M16 with a street racing rage. The road-legal bike will cost a grand total of $235,000. Many Ducati M16 now brace the streets but the Ducati Desmosedici D16RR NCR is a limited model. It weighs just 144kg of dry weight while pumping 203PS of power on the rear-wheel',
    img:'https://i.ibb.co/smGhk54/9-Ducati-Desmosedici-D16-RR-NCR-M16-235000.jpg'},
    {name:'Suzuki AEM Carbon Fiber Hayabusa',rating:'5',
    price:'200,000',
    description:'Suzuki’s AEM Carbon Fiber Hayabusa was once the world’s fastest bike and is among the world’s most expensive. It was released in 2008 following the 1300cc Hayabusa and passionately integrates the aerodynamic spirit by tuning many parts with carbon fiber for a lightweight body. ',
    img:'https://i.ibb.co/Qpvssn3/11-Suzuki-AEM-Carbon-Fiber-Hayabusa-200000.jpg'},
    {name:'Honda RC213 V-S',
    price:'185,000',
    description:'The Japanese brand Honda is popular around the globe for its massive collection and innovative production so an $185,000 RC213 V-S is no surprise from the company. It weighs roughly 170kg (dry weight) and only 200 units of the sports bike were produced. ',
    img:'https://i.ibb.co/ZKP5kPp/12-Honda-RC213-V-S-185000.jpg'},
    {name:'MTT Turbine Streetfighter',rating:'4.5',
    price:'175,000',
    description:'MTT differs from its competitors that directly produce exclusive and restricted units, by catering to the buyer’s customary specifications. It is not intended for mass production business. The Streetfighter was first revealed in 2006 at the Las Vegas SEMA show. The bike makes a powerful 420 horsepower and reaches a speed of 240 mph. ',
    img:'https://i.ibb.co/MnJdry9/13-MTT-Turbine-Streetfighter-175000.jpg'},
    {name:'Icon Sheene',rating:'4.5',
    price:'172,000',
    description:'The Icon Sheene pays homage to the renowned British motorcycle racer and World GP champion Barry Sheene with its exclusive production that is limited to only 52 units and each costs a $172,000. The price is not astounding when a hand-built 1400 CC Suzuki engine is used that transmits 250 hp to the rear wheel. ',
    img:'https://i.ibb.co/kgMW9s8/14.jpg'},
    {name:'NCR Leggera 1200 Titanium Special',rating:'4.5',
    price:'148,000',
    description:'NCR’s Leggera is treated with extravagant modifications and fine-tuning in various features to further reduce the weight so the bike can produce an exemplary speed. To achieve the desired weight the frame is made of hand-built titanium and uses carbon fiber. A 1200cc engine powers an intense 132 horsepower.',
    img:'https://i.ibb.co/JHFftvf/15-NCR-Leggera-1200-Titanium-Special-148000.jpg'}
]